#!/bin/bash
echo "=== 心理学刷题宝典部署脚本 ==="
echo ""
echo "网站已部署到 Netlify"
echo ""
echo "访问地址: https://chimerical-pixie-ba628b.netlify.app"
echo "密码: My-Drop-Site"
echo ""
echo "=== 快速访问 ==="
echo ""
echo "1. 复制下面的链接到浏览器:"
echo "   https://chimerical-pixie-ba628b.netlify.app"
echo ""
echo "2. 输入密码: My-Drop-Site"
echo ""
echo "3. 注册账号或登录"
echo ""
echo "4. 开始刷题！"
echo ""
echo "=== 功能说明 ==="
echo ""
echo "- 顺序刷题: 按题号顺序练习"
echo "- 随机刷题: 随机抽取题目"
echo "- 错题重做: 重新做错过的题目"
echo "- 收藏题目: 收藏重要题目"
echo "- 模拟考试: 模拟考试环境"
echo "- 学习统计: 查看学习进度"
echo ""
echo "=== 本地使用 ==="
echo ""
echo "项目文件位于: C:\Users\22457\Desktop\psychology-quiz"
echo "可以直接在浏览器中打开 index.html 文件使用"
